server:
  port: ${PORT:8008}

spring:
  application:
    name: payment-gateway-service
  output:
    ansi:
      enabled: always
  main:
    banner-mode: off

logging:
  level:
    root: INFO
    com.gdb.payment: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} - %clr(%-5level) %clr(%logger{0}){cyan} : %msg%n"

springdoc:
  api-docs:
    path: /api/v1/api-docs
  swagger-ui:
    path: /docs
