package com.gdb.transactions.service.impl;

import com.gdb.transactions.client.AccountServiceClient;
import com.gdb.transactions.client.PaymentGatewayClient;
import com.gdb.transactions.client.dto.AccountOperationResponse;
import com.gdb.transactions.client.dto.AccountResponse;
import com.gdb.transactions.client.dto.PaymentGatewayResponse;
import com.gdb.transactions.domain.enums.TransactionType;
import com.gdb.transactions.domain.model.FundTransfer;
import com.gdb.transactions.domain.model.TransactionLog;
import com.gdb.transactions.dto.request.FundTransferRequest;
import com.gdb.transactions.dto.response.FundTransferResponse;
import com.gdb.transactions.exception.TransactionException;
import com.gdb.transactions.exception.custom.InsufficientFundsException;
import com.gdb.transactions.repository.FundTransferRepository;
import com.gdb.transactions.service.TransactionLogService;
import com.gdb.transactions.service.TransferLimitService;
import com.gdb.transactions.service.TransferService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;

/**
 * Implementation of TransferService.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class TransferServiceImpl implements TransferService {

        private final AccountServiceClient accountServiceClient;
        private final PaymentGatewayClient paymentGatewayClient;
        private final FundTransferRepository fundTransferRepository;
        private final TransactionLogService transactionLogService;
        private final TransferLimitService transferLimitService;

        @Override
        @Transactional
        public FundTransferResponse processTransfer(FundTransferRequest request) {
                log.info("Processing transfer from account: {} to account: {}, amount: {}",
                                request.getFromAccount(), request.getToAccount(), request.getAmount());

                try {
                        // 1. Validate input
                        if (request.getFromAccount().equals(request.getToAccount())) {
                                throw new TransactionException("SAME_ACCOUNT_TRANSFER",
                                                "Cannot transfer to the same account");
                        }

                        // 2. Validate source account exists and is active
                        AccountResponse fromAccount = accountServiceClient.validateAccount(request.getFromAccount());
                        if (!fromAccount.getIsActive()) {
                                throw new TransactionException("SOURCE_ACCOUNT_INACTIVE",
                                                "Source account is not active");
                        }

                        // 2.1 Check for sufficient funds
                        if (fromAccount.getBalance() != null
                                        && fromAccount.getBalance().compareTo(request.getAmount()) < 0) {
                                throw new InsufficientFundsException("Insufficient balance in source account");
                        }

                        // 3. Validate destination account exists and is active
                        AccountResponse toAccount = accountServiceClient.validateAccount(request.getToAccount());
                        if (!toAccount.getIsActive()) {
                                throw new TransactionException("DESTINATION_ACCOUNT_INACTIVE",
                                                "Destination account is not active");
                        }

                        // 4. Verify PIN for source account
                        boolean pinValid = accountServiceClient.verifyPin(request.getFromAccount(), request.getPin());
                        if (!pinValid) {
                                throw new TransactionException("INVALID_PIN", "Invalid PIN provided");
                        }

                        // 5. Check transfer limits
                        transferLimitService.validateTransferLimits(request.getFromAccount(), request.getAmount());

                        // 5.5 Payment Gateway - Second-Level Validation
                        log.info("Sending transaction to Payment Gateway for second-level validation...");
                        PaymentGatewayResponse gatewayResponse = paymentGatewayClient.processPayment(
                                        request.getFromAccount(),
                                        request.getToAccount(),
                                        request.getAmount(),
                                        request.getTransferMode().name(),
                                        null // reference_id generated by gateway
                        );

                        if (gatewayResponse == null || !gatewayResponse.isSuccess()) {
                                String gatewayMsg = gatewayResponse != null
                                                ? gatewayResponse.getMessage()
                                                : "No response from Payment Gateway";
                                log.error("Payment Gateway REJECTED transaction: {}", gatewayMsg);
                                throw new TransactionException("PAYMENT_GATEWAY_REJECTED", gatewayMsg);
                        }
                        log.info("Payment Gateway APPROVED: gatewayRefId={}", gatewayResponse.getGatewayRefId());

                        // 6. Debit source account
                        AccountOperationResponse debitResponse = accountServiceClient.debitAccount(
                                        request.getFromAccount(),
                                        request.getAmount(),
                                        "Transfer to " + request.getToAccount() + ": " +
                                                        (request.getDescription() != null ? request.getDescription()
                                                                        : "Fund transfer"));

                        // 7. Credit destination account
                        AccountOperationResponse creditResponse = accountServiceClient.creditAccount(
                                        request.getToAccount(),
                                        request.getAmount(),
                                        "Transfer from " + request.getFromAccount() + ": " +
                                                        (request.getDescription() != null ? request.getDescription()
                                                                        : "Fund transfer"));

                        // 8. Record fund transfer
                        FundTransfer fundTransfer = FundTransfer.builder()
                                        .fromAccount(request.getFromAccount())
                                        .toAccount(request.getToAccount())
                                        .transferAmount(request.getAmount())
                                        .transferMode(request.getTransferMode())
                                        .build();

                        FundTransfer savedTransfer = fundTransferRepository.save(fundTransfer);

                        // 9. Log transactions for both accounts
                        // Log for source account (debit)
                        TransactionLog debitLog = TransactionLog.builder()
                                        .accountNumber(request.getFromAccount())
                                        .amount(request.getAmount())
                                        .transactionType(TransactionType.TRANSFER)
                                        .referenceId(savedTransfer.getId())
                                        .description("Transfer to account " + request.getToAccount() + ": " +
                                                        (request.getDescription() != null ? request.getDescription()
                                                                        : "Fund transfer"))
                                        .mode(request.getTransferMode().name())
                                        .status("SUCCESS")
                                        .build();

                        transactionLogService.logTransaction(debitLog);

                        // Log for destination account (credit)
                        TransactionLog creditLog = TransactionLog.builder()
                                        .accountNumber(request.getToAccount())
                                        .amount(request.getAmount())
                                        .transactionType(TransactionType.TRANSFER)
                                        .referenceId(savedTransfer.getId())
                                        .description("Transfer from account " + request.getFromAccount() + ": " +
                                                        (request.getDescription() != null ? request.getDescription()
                                                                        : "Fund transfer"))
                                        .mode(request.getTransferMode().name())
                                        .status("SUCCESS")
                                        .build();

                        transactionLogService.logTransaction(creditLog);

                        // 10. Return success response
                        FundTransferResponse response = FundTransferResponse.builder()
                                        .status("SUCCESS")
                                        .transactionId(savedTransfer.getId())
                                        .fromAccount(request.getFromAccount())
                                        .toAccount(request.getToAccount())
                                        .amount(request.getAmount())
                                        .transferMode(request.getTransferMode())
                                        .description(request.getDescription())
                                        .fromAccountNewBalance(debitResponse.getNewBalance())
                                        .toAccountNewBalance(creditResponse.getNewBalance())
                                        .transactionDate(LocalDateTime.now())
                                        .build();

                        log.info("Transfer processed successfully from account: {} to account: {}, transaction ID: {}",
                                        request.getFromAccount(), request.getToAccount(), savedTransfer.getId());

                        return response;

                } catch (TransactionException e) {
                        log.error("Transfer failed from account: {} to account: {} - {}",
                                        request.getFromAccount(), request.getToAccount(), e.getMessage());

                        // Log failed transaction for source account
                        try {
                                TransactionLog failedLog = TransactionLog.builder()
                                                .accountNumber(request.getFromAccount())
                                                .amount(request.getAmount())
                                                .transactionType(TransactionType.TRANSFER)
                                                .description("Failed: " + e.getMessage())
                                                .mode(request.getTransferMode() != null
                                                                ? request.getTransferMode().name()
                                                                : null)
                                                .status("FAILED")
                                                .build();
                                transactionLogService.logTransaction(failedLog);
                        } catch (Exception logEx) {
                                log.error("Failed to log failed transfer: {}", logEx.getMessage());
                        }
                        throw e;
                } catch (Exception e) {
                        log.error("Unexpected error during transfer from account: {} to account: {}",
                                        request.getFromAccount(), request.getToAccount(), e);
                        throw new TransactionException("TRANSFER_FAILED", "Transfer operation failed");
                }
        }
}